include ../mingw.conf
OBJS_DIR=../temp/upd_w32_rls
GPP=wine ${MINGW_DIR}\\bin\\mingw32-g++.exe
WINDRES=wine ${MINGW_DIR}\\bin\\windres.exe
CXXFLAGS=-O0 -s
#LIBS=-mwindows -lwsock32 -static-libgcc -static-libstdc++
LIBS=-mwindows -lwsock32 

all: ../temp/upd_w32_rls ../bin/updatem.exe

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/updatem.exe

../bin/updatem.exe: ${OBJS}
	${GPP} ${CXXFLAGS} ${OBJS} ${LIBS} -o $@


${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
