OBJS=${OBJS_DIR}/main.o ${OBJS_DIR}/zockets.o 

${OBJS_DIR}/main.o: main.cpp ../pseint/zockets.h
	${GPP} ${CXXFLAGS} -c main.cpp -o $@

${OBJS_DIR}/zockets.o: ../pseint/zockets.cpp ../pseint/zockets.h
	${GPP} ${CXXFLAGS} -c ../pseint/zockets.cpp -o $@

