include ..\mingw.conf
OBJS_DIR=..\temp\upd_w32_rls
CXXFLAGS=-O2
LIBS=-s -lwsock32 -static-libgcc -mwindows -static-libstdc++

all: ${OBJS_DIR} ..\bin\updatem.exe

include Makefile.common

clean:
	del ${OBJS} ..\bin\updatem.exe ${OBJS_DIR}\manifest.o

${OBJS_DIR}\manifest.o: manifest.xml manifest.rc
	${WINDRES} -i manifest.rc -o $@

..\bin\updatem.exe: ${OBJS_DIR}\manifest.o ${OBJS}
	${GPP} -O0 ${OBJS} ${LIBS} ${OBJS_DIR}\manifest.o -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}
