OBJS_DIR=../temp/upd_lnx_rls
GPP=g++
CXXFLAGS_OPT=-O2
CXXFLAGS=${CXXFLAGS_OPT}
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT}

all: ../temp/upd_lnx_rls ../bin/updatem.bin

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/updatem.bin

../bin/updatem.bin: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
