MINGW_DIR=D:\\mingw
OBJS_DIR=../temp/int_w32_rls
GPP=wine ${MINGW_DIR}\\bin\\mingw32-g++.exe
FLAGS= -O2 -DUSE_ZOCKETS
LIBS= -s -lwsock32 -static-libgcc -static-libstdc++ 

all: ${OBJS_DIR} ../bin/pseint.exe

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseint.exe

../bin/pseint.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
