include ..\mingw.conf
OBJS_DIR=..\temp\int_w32_rls
CXXFLAGS= -O3 -DUSE_ZOCKETS -ffloat-store -DNDEBUG
LIBS= -s -lwsock32 -static-libgcc -static-libstdc++

all: ${OBJS_DIR} ..\bin\pseint.exe

include Makefile.common

clean:
	del ${OBJS} ..\bin\pseint.exe

..\bin\pseint.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

