OBJS_DIR=../temp/int_lnx_rls
GPP=g++
FLAGS= -O3 -DUSE_ZOCKETS -ffloat-store
LIBS= -s  

all: ${OBJS_DIR} ../bin/pseint

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseint

../bin/pseint: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

