OBJS_DIR=../temp/int_lnx_rls
GPP=g++
CXXFLAGS_OPT=-O3 
CXXFLAGS=${CXXFLAGS_OPT} -DUSE_ZOCKETS -ffloat-store -DNDEBUG
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT}  

all: ${OBJS_DIR} ../bin/pseint

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseint

../bin/pseint: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

