OBJS_DIR=../temp/int_m32_rls
GPP=i686-apple-darwin8-g++
CXXFLAGS= -O3 -DUSE_ZOCKETS -ffloat-store -DNDEBUG
LIBS=-s

all: ${OBJS_DIR} ../bin/pseint

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseint

../bin/pseint: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

