#!/bin/bash
if [ "$1" = "" ]; then
  echo use: $1 testname
else
  if ! test -e $1.psc; then
    echo File $1.psc not found
    exit 1
  fi
  if test -e $1.arg; then
    ARGS=$(cat $1.arg)
  else
    ARGS=
  fi
  if test -e $1.out; then
    if ! ../bin/pseint --fortest --rawerrors --nouser --noinput $ARGS $1.psc | diff - $1.out &>/dev/null; then
	echo ""
	../bin/pseint --fortest --rawerrors --nouser --noinput $ARGS $1.psc | diff - $1.out
	echo ""
    fi
  else
      make -f Makefile.lnx -C ../pseint -j 2 || exit 1
      cat $1.psc
      echo === running, args=$ARGS
      ../bin/pseint --fortest --rawerrors --nouser --noinput $ARGS $1.psc > $1.out
      cat $1.out
  fi
fi