OBJS_DIR=../temp/drwE_lnx3_rls
GPP=g++
CXXFLAGS_OPT=-O2
CXXFLAGS=${CXXFLAGS_OPT} `wx-config --cppflags --unicode=yes --version=3.1` -D_FOR_EXPORT -I. -DWX3
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT} `wx-config --libs --unicode=yes --version=3.1` -lX11

all: ${OBJS_DIR} ../bin/psdrawE

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdrawE

../bin/psdrawE: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

