OBJS_DIR=../temp/drwE_lnx_rls
GPP=g++
GCC=gcc
FLAGS= -O2 `wx-config --cppflags --unicode=no` -D_FOR_EXPORT -I.
LIBS= -s  `wx-config --libs --unicode=no` -lwx_gtk2_stc-2.8 

all: ${OBJS_DIR} ../bin/psdrawE

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdrawE

../bin/psdrawE: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

