OBJS_DIR=../temp/drwE_m32_rls
GPP=i686-apple-darwin8-g++
CXXFLAGS= -O2 `/opt/mac/wx/bin/wx-config --cppflags --host=i686-apple-darwin8` -D_FOR_EXPORT -I.
LIBS=-s `/opt/mac/wx/bin/wx-config --libs --host=i686-apple-darwin8` -lwx_mac_stc-2.8-i686-apple-darwin8

all: ${OBJS_DIR} ../bin/psdrawE

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdrawE

../bin/psdrawE: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
