OBJS_DIR=../temp/drwE_m64_rls
GPP=x86_64-apple-darwin18-clang++
CXXFLAGS= -O2 `wx-config --cppflags` -D_FOR_EXPORT -I. -DWX3  -Wno-invalid-source-encoding
LIBS=`wx-config --libs std,stc`

all: ${OBJS_DIR} ../bin/psdrawE

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdrawE

../bin/psdrawE: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
