all: 
	@echo "Targets are: src (solo fuentes), w32(windows installer with wine), lnx (linux version, current architecture), m32 (apple-i686), ppc (apple-powerpc)"

src:
	make -f Makefile.pack clean
	rm -f bin/core
	rm -f bin/gmon.out
	cd .. && tar -czvf pseint/dist/pseint-src-`cat pseint/bin/version`.tgz pseint/license.txt pseint/mingw.conf pseint/Makefile pseint/Makefile.* pseint/fuentes.txt pseint/pseint pseint/updatem pseint/wxPSeInt pseint/psterm pseint/pseval pseint/psexport pseint/psdrawE pseint/psdraw3 pseint/bin pseint/dist/license.txt pseint/dist/log.sh pseint/dist/pseint.nsh pseint/dist/get_arch pseint/dist/Info.plist pseint/test pseint/hoewrap
	@echo 
	@echo -n "DONE: "
	@ls -sh dist/pseint-src-`cat bin/version`.tgz
	@echo

w32:
	make -f Makefile.pack clean
	make -f Makefile.wine
	rm -rf dist/pseint 
	mkdir -p dist/pseint 
	cp -r bin/* dist/pseint/
# 	cp dist/*.dll dist/pseint/
	find bin -type f | sed 's/bin/delete $$INSTDIR/' | sed 's/\//\\/g' > dist/uninstall.nsh
	find bin -type d | sed 's/bin/rmdir $$INSTDIR/'  | sed 's/\//\\/g' | sort -r >>dist/uninstall.nsh
	cd dist && wine c:/nsis/makensis.exe /DPRODUCT_VERSION\=`cat pseint/version` pseint.nsh
	cp dist/config.here dist/pseint/config.here
	cd dist && zip -qr -9 -Z bzip2 pseint-w32-`cat pseint/version`.zip pseint
#	ls -sh pseint-w32-`cat pseint/version`.*
	@echo 
	@echo -n "DONE: "
	@ls -sh dist/pseint-w32-`cat bin/version`.*
	@echo

lnx:
	make -f Makefile.pack clean
	make -f Makefile.lnx -C psterm
	make -f Makefile.lnx -C hoewrap
	make -f Makefile.lnx -C wxPSeInt
	make -f Makefile.lnx -C pseval
	make -f Makefile.lnx -C psdrawE
	make -f Makefile.`./dist/get_arch` -C psdraw3
	make -f Makefile.lnx -C pseint
	make -f Makefile.lnx -C psexport
	make -f Makefile.lnx -C updatem
	rm -rf dist/pseint 
	mkdir -p dist/pseint 
	cp -r bin/* dist/pseint/
	cp dist/log.sh dist/pseint/
	cd dist && tar -czvf pseint-`./get_arch`-`cat pseint/version`.tgz pseint 
	@echo 
	@echo -n "DONE: "
	@ls -sh dist/pseint-`dist/get_arch`-`cat bin/version`.tgz
	@echo

dist/mnt:
	mkdir -p dist/mnt

m32: dist/mnt
	make -f Makefile.pack clean
	make -f Makefile.m32
	rm -rf dist/pseint.app
	mkdir -p dist/pseint.app
	mkdir -p dist/pseint.app/Contents
	mkdir -p dist/pseint.app/Contents/MacOS
	mkdir -p dist/pseint.app/Contents/Resources
	cp -r bin/* dist/pseint.app/Contents/Resources
	mv dist/pseint.app/Contents/Resources/wxPSeInt dist/pseint.app/Contents/MacOS/pseint
	cp dist/Info.plist dist/pseint.app/Contents/
	cp bin/imgs/icon.icns dist/pseint.app/Contents/Resources/pseint.icns

	tar -czvf dist/pseint-m32-`cat bin/version`.tgz -C dist pseint.app
	@echo 
	@echo -n "DONE: "
	@ls -sh dist/pseint-m32-`cat bin/version`.tgz
	@echo

ppc: dist/mnt
	make -f Makefile.pack clean
	make -f Makefile.ppc
	rm -rf dist/pseint.app
	mkdir -p dist/pseint.app
	mkdir -p dist/pseint.app/Contents
	mkdir -p dist/pseint.app/Contents/MacOS
	mkdir -p dist/pseint.app/Contents/Resources
	cp -r bin/* dist/pseint.app/Contents/Resources
	mv dist/pseint.app/Contents/Resources/wxPSeInt dist/pseint.app/Contents/MacOS/pseint
	cp dist/Info.plist dist/pseint.app/Contents/
	cp bin/imgs/icon.icns dist/pseint.app/Contents/Resources/pseint.icns

	tar -czvf dist/pseint-ppc-`cat bin/version`.tgz -C dist pseint.app
	@echo 
	@echo -n "DONE: "
	@ls -sh dist/pseint-ppc-`cat bin/version`.tgz
	@echo

clean:
	rm -f bin/temp.psd
	rm -f bin/log.exe
	rm -f bin/updatem.bin
	rm -f bin/updatem.exe
	rm -f bin/pseint
	rm -f bin/pseint.exe
	rm -f bin/wxPSeInt
	rm -f bin/wxPSeInt.bin
	rm -f bin/wxPSeInt.exe
	rm -f bin/psterm
	rm -f bin/psterm.exe
	rm -f bin/psdraw3
	rm -f bin/psdraw3.exe
	rm -f bin/psdrawE
	rm -f bin/psdrawE.exe
	rm -f bin/psexport
	rm -f bin/psexport.exe
	rm -f bin/pseval
	rm -f bin/pseval.exe
	rm -f bin/mac-terminal-wrapper.bin
	rm -f bin/core
	rm -f bin/gmon.out
	rm -f bin/*.dll
	
