all: 
	make -C pseint -f Makefile.m32
	make -C psdraw -f Makefile.m32
	make -C psexport -f Makefile.m32
	make -C wxPSeInt -f Makefile.m32
	make -C updatem -f Makefile.m32

clean: 
	make -C pseint -f Makefile.m32 clean
	make -C psdraw -f Makefile.m32 clean
	make -C psexport -f Makefile.m32 clean
	make -C wxPSeInt -f Makefile.m32 clean
	make -C updatem -f Makefile.m32 clean
