all: 
	make -C pseint -f Makefile.w32
	make -C psdraw -f Makefile.w32
	make -C psexport -f Makefile.w32
	make -C wxPSeInt -f Makefile.w32
	make -C updatem -f Makefile.w32

clean: 
	make -C pseint -f Makefile.w32 clean
	make -C psdraw -f Makefile.w32 clean
	make -C wxPSeInt -f Makefile.w32 clean
	make -C psexport -f Makefile.w32 clean
	make -C updatem -f Makefile.w32 clean

