all: 
	make -C pseint -f Makefile.ppc
	make -C psdraw -f Makefile.ppc
	make -C psexport -f Makefile.ppc
	make -C wxPSeInt -f Makefile.ppc
	make -C updatem -f Makefile.ppc

clean: 
	make -C pseint -f Makefile.ppc clean
	make -C psdraw -f Makefile.ppc clean
	make -C psexport -f Makefile.ppc clean
	make -C wxPSeInt -f Makefile.ppc clean
	make -C updatem -f Makefile.ppc clean
