RANDOMIZE TIMER
DIM s AS STRING
DIM x AS DOUBLE
x = 1.5
PRINT SQR(x)
PRINT ABS(x)
PRINT LOG(x)
PRINT EXP(x)
PRINT SIN(x)
PRINT COS(x)
PRINT TAN(x)
PRINT ARCSIN(x)
PRINT ARCCOS(x)
PRINT ATN(x)
PRINT CINT(x)
PRINT INT(x)
PRINT INT(RND*15)
s = "Hola"
PRINT LEN(s)
PRINT LCASE$(s)
PRINT UCASE$(s)
PRINT MID$(s,1,2)
PRINT s+" Mundo"
PRINT "Mundo "+s
PRINT VAL("15.5")
PRINT STR$(15.5)

FUNCTION ARCSIN(x)
	IF x <= 1 AND x >= -1 THEN
		ARCSIN = ATN(x / SQR(1 - (x * x)))
	ELSE
		PRINT "Domain Error"
		END
	END IF
END FUNCTION

FUNCTION ARCCOS(x)
	IF x <= 1 AND x >= -1 THEN
		ARCCOS = (2 * ATN(1)) - ATN(x / SQR(1 - x * x))
	ELSE
		PRINT "Domain Error"
		END
	END IF
END FUNCTION  
