OBJS_DIR=../temp/drw3_m32_rls
GPP=i686-apple-darwin8-g++
CXXFLAGS= -O2 `/opt/mac/wx/bin/wx-config --cppflags --host=i686-apple-darwin8` -D_USE_TEXTURES -D_USE_FONT
LIBS=-framework OpenGL -framework GLUT  `/opt/mac/wx/bin/wx-config --libs --host=i686-apple-darwin8` -lwx_mac_gl-2.8-i686-apple-darwin8

all: ${OBJS_DIR} ../bin/psdraw3

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdraw3

../bin/psdraw3: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

