OBJS_DIR=../temp/drw3_lnx_rls
GPP=g++
GCC=gcc
CXXFLAGS= -O2 `wx-config --cppflags --unicode=no` -D_USE_TEXTURES
LIBS= -s  `wx-config --libs --unicode=no` -lwx_gtk2_stc-2.8  -lGL -lGLU /usr/lib/libglut.a -lpng

all: ${OBJS_DIR} ../bin/psdraw3

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdraw3

../bin/psdraw3: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

