if __name__ == '__main__':
	a = int()
	b = float()
	c = str()
	d = bool()
	a = int(input())
	b = float(input())
	c = input()
	d = bool(input())
	print(a)
	print(b)
	print(c)
	print(d)
	a = int(input())
	b = float(input())
	c = input()
	d = bool(input())
	print(a,b,c,d)
	print("Esta linea no lleva enter al final", end="")
