include ..\mingw.conf
FLAGS=-O2 -I${MISC_DIR}\include
LIBS=-s -mwindows -L${MISC_DIR}\lib -ljpeg -llibpng -lz -static-libgcc -static-libstdc++
OBJS_DIR=..\temp\drw_w32_rls
OBJS=${OBJS_DIR}\main.o

all: ${OBJS_DIR} ..\bin\psdraw.exe

clean:
	del ${OBJS} ..\bin\psdraw.exe

..\bin\psdraw.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

${OBJS_DIR}\main.o: main.cpp version.h draw.h CImg.h
	${GPP} ${FLAGS} -c main.cpp -o $@

