GPP=g++
FLAGS=-O2 -fpermissive
LIBS=-s -lpthread -lX11 /usr/lib64/libpng.a /usr/lib64/libjpeg.a /usr/lib64/libz.a
OBJS=../temp/drw_lnx_rls/main.o

all: ../temp/drw_lnx_rls ../bin/psdraw

clean:
	rm -rf ${OBJS} ../bin/psdraw

../bin/psdraw: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

../temp/drw_lnx_rls:
	mkdir -p ../temp/drw_lnx_rls

../temp/drw_lnx_rls/main.o: main.cpp version.h draw.h CImg.h
	${GPP} ${FLAGS} -c main.cpp -o $@

