OBJS=${OBJS_DIR}/Application.o ${OBJS_DIR}/mxFrame.o ${OBJS_DIR}/mxConsole.o 

${OBJS_DIR}/Application.o: Application.cpp Application.h mxFrame.h
	${GPP} ${CXXFLAGS} -c Application.cpp -o $@

${OBJS_DIR}/mxFrame.o: mxFrame.cpp mxFrame.h mxConsole.h
	${GPP} ${CXXFLAGS} -c mxFrame.cpp -o $@

${OBJS_DIR}/mxConsole.o: mxConsole.cpp mxConsole.h
	${GPP} ${CXXFLAGS} -c mxConsole.cpp -o $@

