OBJS_DIR=../temp/trm_m32_rls
GPP=i686-apple-darwin8-g++
CXXFLAGS= -O2 `/opt/mac/wx/bin/wx-config --cppflags --host=i686-apple-darwin8`
LIBS=-s `/opt/mac/wx/bin/wx-config --libs --host=i686-apple-darwin8` -lwx_mac_stc-2.8-i686-apple-darwin8

all: ${OBJS_DIR} ../bin/psterm

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psterm

../bin/psterm: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
