OBJS_DIR=../temp/trm_lnx3_rls
GPP=g++
CXXFLAGS_OPT=-O2
CXXFLAGS=${CXXFLAGS_OPT} `wx-config --cppflags --unicode=yes --version=3.1` -DWX3
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT}  `wx-config --libs --unicode=yes --version=3.1` -lX11

all: ${OBJS_DIR} ../bin/psterm

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psterm

../bin/psterm: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

