include ..\mingw.conf
OBJS_DIR=..\temp\drw2_w32_rls
CXXFLAGS= -O2 -DFREEGLUT_STATIC -I ${OPENGL_DIR}\include
LIBS= -L ${OPENGL_DIR}\lib -s -lfreeglut_static -lopengl32 -lglu32 -lwinmm -lgdi32 -mwindows -static-libgcc -static-libstdc++ -lwsock32

all: ${OBJS_DIR} ..\bin\psdraw2.exe

include Makefile.common

clean:
	rm -rf ${OBJS} ..\bin\psdraw2.exe

..\bin\psdraw2.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

