BASE=/opt/mac
SDK=${BASE}/SDKs/MacOSX10.4u.sdk
OBJS_DIR=../temp/drw2_m32_rls
GPP=i686-apple-darwin8-g++
GCC=gcc
FLAGS= -O2 -I${BASE}/freeglut/i686/include -I${SDK}/usr/X11R6/include
LIBS= -s -lGL -lGLU -lglut  -L${BASE}/freeglut/i686/lib -L${BASE}/SDKs/MacOSX10.4u.sdk/usr/X11R6/lib

all: ${OBJS_DIR} ../bin/psdraw2

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdraw2

../bin/psdraw2: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

