OBJS_DIR=../temp/drw2_m32_rls
GPP=i686-apple-darwin8-g++
FLAGS= -O2
LIBS= -s -lGL -lGLU -lglut  

all: ${OBJS_DIR} ../bin/psdraw2

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psdraw2

../bin/psdraw2: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

