OBJS_DIR=../temp/eval_lnx_rls
GPP=g++
CXXFLAGS_OPT=-O2 -DALLOW_MARKDOWN
CXXFLAGS=${CXXFLAGS_OPT} `wx-config --cppflags --unicode=no --version=2.8`
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT} -lwx_gtk2_stc-2.8 `wx-config --libs --unicode=no --version=2.8` -lX11 -L../temp/hoew_lnx_rls -lhoewrap

all: ${OBJS_DIR} ../bin/pseval

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseval

../bin/pseval: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

