OBJS_DIR=../temp/pseval_ppc_rls
GPP=powerpc-apple-darwin8-g++
CXXFLAGS= -O2 `/opt/mac/wx/bin/wx-config --cppflags --host=powerpc-apple-darwin8` -DALLOW_MARKDOWN
LIBS=-s `/opt/mac/wx/bin/wx-config --libs --host=powerpc-apple-darwin8` -lwx_mac_stc-2.8-powerpc-apple-darwin8 -L../temp/hoew_ppc_rls -lhoewrap

all: ${OBJS_DIR} ../bin/pseval

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/pseval

../bin/pseval: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

