include ..\mingw.conf
OBJS_DIR=..\temp\exp_w32_rls
CXXFLAGS=-O2 -I..\pseint -D_FOR_PSEXPORT
LIBS=-s -static-libgcc -static-libstdc++

all: ${OBJS_DIR} ..\bin\psexport.exe

include Makefile.common

clean:
	del ${OBJS} ..\bin\psexport.exe

..\bin\psexport.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}
