OBJS_DIR=../temp/exp_ppc_rls
GPP=powerpc-apple-darwin8-g++
CXXFLAGS= -O2 -I../pseint -D_FOR_PSEXPORT
LIBS=-s

all: ${OBJS_DIR} ../bin/psexport

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psexport

../bin/psexport: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

