OBJS_DIR=../temp/exp_m64_rls
GPP=x86_64-apple-darwin18-clang++
CXXFLAGS= -O2 -I../pseint -D_FOR_PSEXPORT
LIBS=

all: ${OBJS_DIR} ../bin/psexport

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psexport

../bin/psexport: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

