OBJS_DIR=../temp/exp_lnx_rls
GPP=g++
CXXFLAGS_OPT=-O2
CXXFLAGS=${CXXFLAGS_OPT} -I../pseint -D_FOR_PSEXPORT
LDFLAGS_OPT=-s
LDFLAGS=${LDFLAGS_OPT}

all: ${OBJS_DIR} ../bin/psexport

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psexport

../bin/psexport: ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

