include ../mingw.conf
OBJS_DIR=../temp/exp_w32_rls
GPP=wine ${MINGW_DIR}\\bin\\mingw32-g++.exe
CXXFLAGS=-O2 -I../pseint -D_FOR_PSEXPORT
LIBS=-s -static-libgcc -static-libstdc++ 

all: ../temp/exp_w32_rls ../bin/psexport.exe

include Makefile.common

clean:
	rm -rf ${OBJS} ../bin/psexport.exe

../bin/psexport.exe: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

../temp/exp_w32_rls:
	mkdir -p ../temp/exp_w32_rls
