#ifndef ids_H
#define ids_H

enum {
	mxID_MAIN = wxID_HIGHEST,
		mxID_FILE_NEW, mxID_FILE_OPEN, mxID_FILE_SAVE, mxID_FILE_PRINT, mxID_FILE_SAVE_AS, mxID_FILE_EXIT, mxID_FILE_CLOSE, mxID_FILE_EXPORT_CPP, mxID_FILE_EDIT_FLOW,
		mxID_EDIT_UNDO, mxID_EDIT_REDO, mxID_EDIT_CUT, mxID_EDIT_COPY, mxID_EDIT_PASTE, mxID_EDIT_COMMENT, mxID_EDIT_UNCOMMENT, mxID_EDIT_DUPLICATE, mxID_EDIT_DELETE,
		mxID_EDIT_FIND,	mxID_EDIT_FIND_PREV,mxID_EDIT_FIND_NEXT, mxID_EDIT_REPLACE,mxID_EDIT_SELECT_ALL,mxID_EDIT_TOGGLE_LINES_UP,mxID_EDIT_TOGGLE_LINES_DOWN,
		mxID_EDIT_INDENT_SELECTION,mxID_EDIT_BEAUTIFY_CODE,
		mxID_RUN_RUN, mxID_RUN_STEP_STEP, mxID_RUN_SUBTITLES, mxID_RUN_LAST, mxID_RUN_DRAW_FLOW, mxID_RUN_SAVE_FLOW, mxID_RUN_CHECK, mxID_RUN_SET_INPUT,
		mxID_CONFIG_REALLY_SHOW_DEBUG_PANEL,mxID_CONFIG_SHOW_DEBUG_PANEL,mxID_CONFIG_SHOW_QUICKHELP, mxID_CONFIG_SHOW_RESULTS, mxID_CONFIG_SHOW_TOOLBAR, mxID_CONFIG_COLOUR_SINTAX, mxID_CONFIG_SHOW_VARS, mxID_CONFIG_HIGHLIGHT_BLOCKS, mxID_CONFIG_REORGANIZE_FOR_DEBUG,
		mxID_CONFIG_SHOW_COMMANDS, mxID_CONFIG_SMART_INDENT, mxID_CONFIG_AUTOCOMP, mxID_CONFIG_AUTOCLOSE, mxID_CONFIG_LANGUAGE, mxID_CONFIG_HIGHRES, mxID_CONFIG_RT_SYNTAX, mxID_CONFIG_NASSI_SCHNEIDERMAN,
		mxID_CONFIG_STEPSTEP_L,mxID_CONFIG_STEPSTEP_M,mxID_CONFIG_STEPSTEP_H, mxID_CONFIG_CALLTIP_HELPS, mxID_CONFIG_USE_COLORS, mxID_CONFIG_USE_PSTERM,
		mxID_HELP_INDEX, mxID_HELP_QUICKHELP, mxID_HELP_REFERENCE, mxID_HELP_ABOUT, mxID_HELP_EXAMPLES, mxID_HELP_UPDATES,
		mxID_CMD_ASIGNAR, mxID_CMD_LEER, mxID_CMD_ESCRIBIR, mxID_CMD_PARA, mxID_CMD_SI, mxID_CMD_SEGUN, mxID_CMD_MIENTRAS, mxID_CMD_REPETIR, mxID_CMD_SUBPROCESO,
		mxID_FIND_FIND_PREV,mxID_FIND_REPLACE,mxID_FIND_REPLACE_ALL,mxID_FIND_FIND_NEXT,
		mxID_HELPW, mxID_HELPW_HIDETREE, mxID_HELPW_HOME, mxID_HELPW_NEXT, mxID_HELPW_PREV, mxID_HELPW_COPY, mxID_HELPW_SEARCH, mxID_HELPW_SEARCH_ALL,
		mxID_FILE_SOURCE_HISTORY_0, mxID_FILE_SOURCE_HISTORY_1, mxID_FILE_SOURCE_HISTORY_2, mxID_FILE_SOURCE_HISTORY_3, mxID_FILE_SOURCE_HISTORY_4, mxID_FILE_SOURCE_HISTORY_5,
		mxID_DEBUG_BUTTON,mxID_DEBUG_PAUSE,mxID_DEBUG_STEP,mxID_DEBUG_INSPECT,mxID_DEBUG_SLIDER, mxID_DEBUG_DESKTOP_VARS,mxID_DEBUG_EVALUATE,mxID_DEBUG_HELP,mxID_DEBUG_STEP_IN,mxID_DEBUG_SUBTITLES,
		mxID_DESKTOP_LIST_ADD,mxID_DESKTOP_LIST_EDIT,mxID_DESKTOP_LIST_DELETE,mxID_DESKTOP_LIST_DELETE_ALL,mxID_DESKTOP_LIST_UP,mxID_DESKTOP_LIST_DOWN,
		mxID_HELP_BUTTON, mxID_SOCKET_UPDATES,
		mxID_VIEW_NOTEBOOK_PREV,mxID_VIEW_NOTEBOOK_NEXT,mxID_DO_THAT,
		mxID_HELPER_VARS,mxID_HELPER_DEBUG,mxID_HELPER_COMMANDS,
};

#endif
